# fly.toml app configuration file generated for werewolf-sg-api on 2026-06-06T09:36:58+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'werewolf-sg-api'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 400

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
